name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Install .NET Core environment with .NET 9.0
      - name: Install .NET 9.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      # Restore dependencies
      - name: Restore Dependencies
        run: dotnet restore

      # Build the application
      - name: Build Application
        run: dotnet build --no-restore

      # Run Tests
      - name: Run Tests
        run: dotnet test --no-build --verbosity normal

