name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up .NET Core environment
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      # Restore dependencies
      - name: Restore Dependencies
        run: dotnet restore

      # Build the application
      - name: Build Application
        run: dotnet build --no-restore

      # Run Tests
      - name: Run Tests
        run: dotnet test --no-build --verbosity normal

